backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
- name: settings
  label: Settings
  editor:
    preview: false
  files:
  - name: flavors
    label: Flavors
    file: content/flavors.json
    fields:
    - name: category
      label: Category
      widget: string
    - name: flavors
      label: Flavors
      widget: list
      fields:
      - name: name
        label: Name
        widget: string
      - name: allergens
        label: Allergens
        widget: list
      - name: half-gallon
        label: Half Gallon
        widget: boolean
