backend:
  name: git-gateway
  branch: master

display_url: https://haywardsfamilyicecream.com
media_folder: static/images
public_folder: /images

collections:
  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: General
        file: content/settings/settings.yaml
        fields:
          - name: banner
            label: Banner
            widget: string
          - name: social
            label: Social
            widget: object
            fields:
              - name: type
                label: Type
                widget: select
                options: ['instagram', 'facebook', 'twitter']
              - name: label
                label: Label
                widget: string
              - name: url
                label: Url
                widget: string
          - name: contact
            label: Contact
            widget: list
            fields:
              - name: type
                label: Type
                widget: select
                options: ['phone', 'place', 'email']
              - name: label
                label: Label
                widget: string
              - name: url
                label: Url
                widget: string
              - name: value
                label: Value
                widget: string
