banner: Open daily at 11am!
social:
  - label: Find us on Facebook
    type: facebook
    url: 'https://facebook.com/haywardsofmilford'
contact:
  - label: Give us a call
    type: phone
    url: 'tel:16036728383'
    value: (603) 672-8383
  - label: Come visit us
    type: place
    url: >-
      https://www.google.com/maps?q=Hayward's+Ice+Cream+of+Milford,+Elm+Street,+Milford,+NH
    value: '383 Elm St, Milford, NH 03055'
  - label: Send us a message
    type: email
    url: 'mailto:haywardsofmilford@gmail.com'
    value: haywardsofmilford@gmail.com
